import ApexLineChartCode from "@/app/components/charts/Code/ApexLineChartCode";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Line Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Line",
  },
];
const LineChart = () => {
  return (
    <>
      <BreadcrumbComp title="Chart Apex Line" items={BCrumb} />
      <ApexLineChartCode />
    </>
  );
};

export default LineChart;
