GET http://127.0.0.1:8000/auth/users/me/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5MzYwNDIyLCJpYXQiOjE3MjkzMzg0ODQsImp0aSI6ImZiZTE5ZTg3ZTQzNDRjOGY5OTFhZTIxZDQ1Njk1YjZlIiwidXNlcl9pZCI6Mn0.xBYfPyRgfYQlulxMnAtQFx1SzuJ7zCtuRfn5MX0rTNQjEL6gc0JpvCxG9qt7bQEXjL6DtUqgkPorKjrGX5fm0g