# Generated by Django 5.2.9 on 2026-03-04 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_article_options_alter_questionblock_options_and_more'),
        ('enrollments', '0004_courseprogress_contentprogress_quizsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentprogress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentprogress',
            name='course_progress',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='enrollment',
        ),
        migrations.CreateModel(
            name='EnrollmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lectures', models.PositiveIntegerField(default=0)),
                ('completed_lectures', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0)),
                ('total_video_seconds', models.PositiveIntegerField(default=0)),
                ('watched_video_seconds', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.content')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='enrollments.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='enrollments.enrollmentprogress')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.content')),
            ],
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='enrollments.lectureprogress'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollments.lectureprogress')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoProgress',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='ContentProgress',
        ),
    ]
