# Generated by Django 5.2.9 on 2026-03-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_remove_contentprogress_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureprogress',
            name='course_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='enrollments.enrollmentprogress'),
        ),
    ]
