# Generated by Django 5.2.9 on 2026-03-14 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_question_allow_multiple_answers'),
        ('enrollments', '0006_alter_lectureprogress_course_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.question'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='questionsubmission',
            unique_together={('submission', 'question')},
        ),
    ]
