# Generated by Django 5.2.9 on 2026-03-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_alter_quizsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='text_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
