# Generated by Django 5.2.9 on 2026-03-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_quizsubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
