# Generated by Django 5.2.9 on 2026-03-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_questionsubmission_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
