# Generated by Django 5.2.9 on 2026-03-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0011_questionsubmission_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='remaining_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('is_paused', 'Paused'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
