# Generated by Django 5.2.9 on 2026-03-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0012_quizsubmission_expires_at_quizsubmission_is_paused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='is_paused',
        ),
    ]
