# Generated by Django 5.2.9 on 2026-03-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0013_remove_quizsubmission_is_paused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='last_activity_at',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='time_spent_seconds',
        ),
    ]
