# Generated by Django 5.2.9 on 2026-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0014_remove_quizsubmission_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
