# Generated by Django 5.2.9 on 2026-04-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0015_alter_quizsubmission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='remaining_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
