# Generated by Django 5.2.9 on 2026-02-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_order_options_alter_usersubscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at']},
        ),
    ]
