import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
export const metadata: Metadata = {
  title: "Maintenance",
  description: "Generated by create next app",
};
const Maintenance = () => {
  return (
    <>
      <div className="h-screen flex items-center  justify-center bg-white dark:bg-darkgray ">
        <div className="text-center max-w-lg mx-auto">
          <Image src={"/images/backgrounds/maintenance.svg"} alt="error" className="mb-4" width={600} height={380}/>
          <h1 className="text-dark dark:text-white text-4xl mb-6">Maintenance Mode!!!</h1>
          <h6 className="text-xl text-dark dark:text-white">Website is Under Construction. Check back later!</h6>
          <Button className="w-fit mt-6 mx-auto">
            <Link href={"/"}>
              Go Back to Home
            </Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Maintenance;
