# Generated by Django 5.2.9 on 2026-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
