
import React from "react";
import BreadcrumbComp from "../../layout/shared/breadcrumb/BreadcrumbComp";
import type { Metadata } from "next";
import ApexAreaChartCode from "@/app/components/charts/Code/ApexAreaChartCode";
export const metadata: Metadata = {
  title: "Area Chart",
  description: "Generated by create next app",
};

const BCrumb = [
  {
    to: "/",
    title: "Home",
  },
  {
    title: "Chart Apex Area",
  },
];
const AreaChart = () => {

  return (
    <>
      <BreadcrumbComp title="Chart Apex Area" items={BCrumb} />
      <ApexAreaChartCode/>
    </>
  );
};

export default AreaChart;
