import React from "react";
import type { Metadata } from "next";
import {  Manrope } from "next/font/google";
import "./css/globals.css";
import "../utils/i18n";
import NextTopLoader from "nextjs-toploader";
import { CustomizerContextProvider } from "./context/CustomizerContext";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Matdash - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${manrope.className}`}>
        <NextTopLoader color="#5d87ff" showSpinner={false} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CustomizerContextProvider>
              {children}
          </CustomizerContextProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
