# Generated by Django 5.2.9 on 2026-01-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='courses/posters/'),
        ),
    ]
