# Generated by Django 5.2.9 on 2026-01-17 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('courses', '0003_course_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Course Content', 'verbose_name_plural': 'Course Contents'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='essayanswer',
            options={'verbose_name': 'Essay Answer', 'verbose_name_plural': 'Essay Answers'},
        ),
        migrations.AlterModelOptions(
            name='fileuploadanswer',
            options={'verbose_name': 'File Upload Answer', 'verbose_name_plural': 'File Upload Answers'},
        ),
        migrations.AlterModelOptions(
            name='fillblankanswer',
            options={'verbose_name': 'Fill in the Blank Answer', 'verbose_name_plural': 'Fill in the Blank Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
        migrations.AlterModelOptions(
            name='truefalseanswer',
            options={'verbose_name': 'True/False Answer', 'verbose_name_plural': 'True/False Answers'},
        ),
        migrations.AddField(
            model_name='course',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
