# Generated by Django 5.2.9 on 2026-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_answer_options_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of course requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes'),
        ),
    ]
