# Generated by Django 5.2.9 on 2026-01-30 12:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_short_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
