# Generated by Django 5.2.9 on 2026-01-30 13:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='can_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
