# Generated by Django 5.2.9 on 2026-01-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_content_can_preview_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='can_preview',
        ),
    ]
