# Generated by Django 5.2.9 on 2026-01-31 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True),
        ),
    ]
