# Generated by Django 5.2.9 on 2026-02-02 20:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
