# Generated by Django 5.2.9 on 2026-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('attachment', 'Attachment'), ('assignment', 'Assignment'), ('article', 'Article')], max_length=20),
        ),
    ]
