# Generated by Django 5.2.9 on 2026-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_main_preview',
            field=models.BooleanField(default=False),
        ),
    ]
