# Generated by Django 5.2.9 on 2026-02-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Total duration of all contents in minutes', null=True),
        ),
    ]
