# Generated by Django 5.2.9 on 2026-02-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Required if access_type is limited', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='access_type',
            field=models.CharField(choices=[('lifetime', 'Lifetime'), ('limited', 'Limited')], default='lifetime', max_length=20),
        ),
    ]
