# Generated by Django 5.2.9 on 2026-02-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestionSubmission',
        ),
        migrations.DeleteModel(
            name='QuizSubmission',
        ),
    ]
