# Generated by Django 5.2.9 on 2026-02-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_quizsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionblock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
