# Generated by Django 5.2.9 on 2026-02-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_article_options_alter_questionblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionblock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
