# Generated by Django 5.2.9 on 2026-03-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_question_quiz_segment_question_segment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Segment', 'verbose_name_plural': 'Segments'},
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='name',
            new_name='title',
        ),
    ]
