# Generated by Django 5.2.9 on 2026-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_segment_options_rename_name_segment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='label',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
