# Generated by Django 5.2.9 on 2026-03-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_suggestion_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
