# Generated by Django 5.2.9 on 2026-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_quiz_title_quiz_show_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='can_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='can_retake',
            field=models.BooleanField(default=False),
        ),
    ]
