# Generated by Django 5.2.9 on 2026-03-18 20:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_quiz_can_pause_quiz_can_retake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truefalseanswer',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_explanation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_final_score',
            field=models.BooleanField(default=False),
        ),
    ]
