# Generated by Django 5.2.9 on 2026-03-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_rename_correct_truefalseanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
