# Generated by Django 5.2.9 on 2026-03-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_question_answer_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='require_review',
            field=models.BooleanField(default=False),
        ),
    ]
