# Generated by Django 5.2.9 on 2026-03-22 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_quiz_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('attachment', 'Attachment'), ('assignment', 'Assignment'), ('article', 'Article'), ('conference', 'Conference')], max_length=20),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('room_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='courses.content')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
