# Generated by Django 5.2.9 on 2026-03-28 20:54

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_content_type_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='segment',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QuestionBlock',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
