# Generated by Django 5.2.9 on 2026-03-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_remove_segment_quiz_remove_question_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_minutes',
        ),
    ]
