# Generated by Django 5.2.9 on 2026-03-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_remove_quiz_time_limit_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
