# Generated by Django 5.2.9 on 2026-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_remove_course_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
    ]
