# Generated by Django 5.2.9 on 2026-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_section_is_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_expanded',
            field=models.BooleanField(default=False),
        ),
    ]
