# Generated by Django 5.2.9 on 2026-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_content_is_expanded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='truefalseanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
