# Generated by Django 5.2.9 on 2026-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
