# Generated by Django 5.2.9 on 2026-04-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_alter_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
