# Generated by Django 5.2.9 on 2026-04-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_document_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
