# Generated by Django 5.2.9 on 2026-04-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_main_preview',
        ),
        migrations.AddField(
            model_name='content',
            name='is_main_preview',
            field=models.BooleanField(default=False),
        ),
    ]
