# Generated by Django 5.2.9 on 2026-04-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_path_category_path_name_and_more'),
        ('courses', '0051_remove_video_is_main_preview_content_is_main_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_courses', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.question'),
        ),
    ]
