# Generated by Django 5.2.9 on 2026-04-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_course_sub_category_alter_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='can_retake',
        ),
    ]
