# Generated by Django 5.2.9 on 2026-02-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
    ]
