# Generated by Django 5.2.9 on 2026-02-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rating_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
