# Generated by Django 5.2.9 on 2026-02-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
    ]
