import React from "react";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../css/globals.css";
import NextTopLoader from "nextjs-toploader";
import { CustomizerContextProvider } from "../context/CustomizerContext";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from 'sonner'
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { ReactQueryProvider } from "@/hooks/react-query-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Matdash - Nextjs",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const session = await auth();

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const dir = locale === "ar" ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`${manrope.className}`}>
        <NextTopLoader color="#5d87ff" showSpinner={false} />
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={false}
            disableTransitionOnChange
          >
            <CustomizerContextProvider>
              <ReactQueryProvider>
                <SessionProvider session={session}>
                  {children}
                  <Toaster richColors position="top-right" />
                </SessionProvider>
              </ReactQueryProvider>
            </CustomizerContextProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
