# Generated by Django 5.2.9 on 2026-01-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_role_name_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
