# Generated by Django 5.2.9 on 2026-01-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_avatar'),
    ]

    operations = [
        
    ]
