# Generated by Django 5.2.9 on 2026-01-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_avatar'),
    ]

    operations = [
       
    ]
