# Generated by Django 5.2.9 on 2026-01-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.role'),
        ),
    ]
