# Generated by Django 5.2.9 on 2026-02-15 18:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
