# Generated by Django 5.2.9 on 2026-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_github_profile_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn ID'),
        ),
    ]
