# Generated by Django 5.2.9 on 2026-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_github_alter_profile_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='github_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Linkedin ID'),
        ),
    ]
