# Generated by Django 5.2.9 on 2026-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='editor/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
